### ISSUE TITLE
how can also dismiss the menu if tap anywhere else on the screen?

### ISSUE THREAD

**Issue by jasan-s** [feiin/DWBubbleMenuButton.Swift#1]
Newbie question, Currently the menu retracts if you click the tap button again, but I also want the menu to retract if the user taps anywhere else on the screen expect the buttons. ANy suggestions?

**Comment by jasan-s** [comment]
The problem I'm running into is that I am implementing this in navbar with tabbarcontroller, what happens is that if i tap the button to open the menu and then click on the different tab without collapsing the bubble menu.  And then if I come back to the same tab, the bubble menu is visually still open but in code it still thinks it is collapsed, that leads to weird behavior of adding another subview

**Comment by yangyin5127** [comment]
call `dismissButtons()` method when you need hide.

```
downMenuButton.dismissButtons()
upMenuView.dismissButtons()
```

**Comment by jasan-s** [comment]
cool thanks
